{{- $jenkinsName := include "jenkins.fullname" . -}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $jenkinsName }}-worker-role
  namespace: {{ .Values.Agent.WorkerNamespace }}
rules:
- apiGroups:
  - gitops.kubesphere.io
  resources:
  - applications
  verbs:
  - get

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $jenkinsName }}-worker-role-binding
  namespace: {{ .Values.Agent.WorkerNamespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.Agent.WorkerNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ $jenkinsName }}-worker-role
  apiGroup: rbac.authorization.k8s.io
