apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterTemplate
metadata:
  name: ci
  annotations:
    devops.kubesphere.io/displayNameEN: &defaultDisplayName "Continuous Integration (CI)"
    devops.kubesphere.io/displayNameZH: "持续集成 (CI)"
    devops.kubesphere.io/discriptionEN: &defaultDescription "Continuous integration (CI) is the process of automatically detecting, pulling, building, and (in most cases) unit testing after source code changes."
    devops.kubesphere.io/discriptionZH: "持续集成（CI）是在源代码变更后自动检测、拉取、构建和（在大多数情况下）进行单元测试的过程。"
    devops.kubesphere.io/displayName: *defaultDisplayName
    devops.kubesphere.io/description: *defaultDescription
  labels:
    devops.kubesphere.io/offcial: "true"
spec:
  template: |
    pipeline {
        agent {
            node {
              label 'base'
            }
        }
        environment {
            DOCKER_CREDENTIAL_ID = 'dockerhub'
            KUBECONFIG_CREDENTIAL_ID = 'kubeconfig'
            REGISTRY = 'docker.io'
            DOCKERHUB_NAMESPACE = 'shaowenchen'
            APP_NAME = 'devops-python-sample'
            SONAR_CREDENTIAL_ID = 'sonar-token'
        }
        parameters {
            string(name: 'BRANCH_NAME', defaultValue: 'master', description: '')
        }
        stages {
            stage('clone code') {
                steps {
                    container('base') {
                        checkout([$class: 'GitSCM', branches: [[name: '*/$BRANCH_NAME']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/kubesphere/devops-python-sample.git']]])
                    }
                }
            }
            stage('build & push') {
                steps {
                    container('base') {
                        withCredentials([usernamePassword(credentialsId : "$DOCKER_CREDENTIAL_ID" ,passwordVariable: 'DOCKER_PASSWORD' ,usernameVariable: 'DOCKER_USERNAME' ,)]) {
                            sh 'echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
                            sh 'docker build -f Dockerfile-online -t $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER .'
                            sh 'docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER'
                        }
                    }
                }
            }
        }
    }
