replicaCount: 1

image:
  # support 'ghcr.io/kubesphere' or 'kubespheredev'
  registry: ghcr.io/kubesphere
  controller:
    repository: devops-controller
    tag: master
  apiserver:
    repository: devops-apiserver
    tag: master
  tools:
    repository: devops-tools
    tag: master
  pullPolicy: IfNotPresent

gcJobs:
  # gcJobs.maxAge -- Max age from which `PipelineRun`s will be deleted
  maxAge: 168h
  # gcJobs.maxCount -- Max count from which `PipelineRun`s will be deleted
  maxCount: 30
  # gcJobs.schedule -- Cron expression to periodically delete `PipelineRun`s
  schedule: "0/30 * * * *"
  # gcJobs.failedJobsHistoryLimit -- Drives the failed jobs history limit
  failedJobsHistoryLimit: 1
  # gcJobs.successfulJobsHistoryLimit -- Drives the successful jobs history limit
  successfulJobsHistoryLimit: 3
  # gcJobs.concurrencyPolicy -- Drives the job's concurrency policy
  concurrencyPolicy: Forbid

authentication:
  # If not set, jwt tools will generate and set it automatically
  jwtSecret: ""

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

s2i:
  enabled: true

jenkins:
  enabled: true

argocd:
  enabled: true
  namespace: argocd
